# Extraire les donn√©es

# ¬´ Snscrape ¬ª est un scraper pour les services de r√©seaux sociaux (SNS). Il r√©cup√®re des √©l√©ments tels que les profils d'utilisateurs, les hashtags ou les recherches et renvoie les √©l√©ments d√©couverts.  On a collect√© 500 tweets porte le mot ‚Äòangoisse‚Äô pour la date 2022/02/05 et l‚Äôemport√© sous forme csv.

In [2]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

In [3]:
tweets_list1 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('anguish until:2022-02-05').get_items()):
    if i>500:
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.likeCount, tweet.user.displayname, tweet.lang])
    
# Creating a dataframe from the tweets list above
tweets_df1 = pd.DataFrame(tweets_list1, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Like Count', 'Display Name', 'Language'])

In [6]:
tweets_df1.to_csv('data extraction.csv')

In [7]:
tweets_df1

,Datetime,Tweet Id,Text,Username,Like Count,Display Name,Language
0,2022-02-04 23:58:25+00:00,1489750218992078850,@KingOfTheFay \n\nShe‚Äôd like to kiss that bloo...,BreathOfAnguish,1,ùêÄùñûùñåùêÆùñèùê¨ùñç (SH),en
1,2022-02-04 23:58:00+00:00,1489750117041074176,@libsoftiktok Life hack- step 1 try opening th...,bj78us,0,Brandon,en
2,2022-02-04 23:56:08+00:00,1489749644376784909,@Corgimine @BTSsmash @chag_spc @Light_S21 @Twe...,docghosteggo,0,Ghostboi,tl
3,2022-02-04 23:55:30+00:00,1489749488721879042,"‚ÄúSearing in blank of night, the serpent‚Äôs stin...",AnalectsofAlex,10,Alex,en
4,2022-02-04 23:53:50+00:00,1489749068137984004,@amayabutsecret Honestly Brie shilling for NFT...,ShootingTsars,3,#1 Transgender (World Record),en
...,...,...,...,...,...,...,...
496,2022-02-04 13:48:03+00:00,1489596615446966280,I listen to A Seat at The Table in times of an...,Courtdog_,1,ÿßÿ≥ŸÖÿ± Ÿäÿß ÿßÿ≥ŸÖÿ±ÿßŸÜŸä,en
497,2022-02-04 13:47:47+00:00,1489596551857324037,@emptyboxie Aku udah langsung ungsikan si dede...,VampirEllachan,1,Lady of Night Anguish,in
498,2022-02-04 13:47:07+00:00,1489596380012232711,Who uttered the following words: ‚ÄòI only compl...,MentallyillHuey,0,Shaykh Huey‚õ∞,und
499,2022-02-04 13:46:57+00:00,1489596340888039432,@pemujanaspad Aminnnn.. Pdhl dah mikir weekend...,VampirEllachan,0,Lady of Night Anguish,in
500,2022-02-04 13:46:01+00:00,1489596106577420292,@urfavgin Amiiinnnüò≠üò≠üò≠,VampirEllachan,0,Lady of Night Anguish,en

In [8]:
Data_Ext = pd.read_csv('data extraction.csv')